server:
  port: 9003
spring:
  profiles:
    active: celebrity-route
  application:
    name: server-gateway
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9001/eureka/

##  Predict 实例
---
spring:
  cloud:
    gateway:
      discovery:
        locator:
         enabled: true
         lowerCaseServiceId: true
      routes:
      - id: user-router
        uri: lb://celebrity-server-user
        predicates:
        - Path=/api/user/**
        filters:
        - StripPrefix=1

      - id: order-router
        uri: lb://celebrity-server-order
        predicates:
        - Path=/api/order/**
        filters:
        - StripPrefix=2
  profiles: celebrity-route

